# Generated by Django 4.2.7 on 2025-10-27 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dueño',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False, verbose_name='Esterilizado'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Peso (kg)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='mascotas.dueño', verbose_name='Dueño'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(default=0, verbose_name='Edad (años)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=50, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Raza'),
        ),
    ]
