# Generated by Django 4.2.7 on 2025-10-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_dueño_direccion_mascota_esterilizado_mascota_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/fotos/', verbose_name='Foto'),
        ),
    ]
