# Generated by Django 4.2.7 on 2025-10-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_remove_mascota_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(default=False, verbose_name='Esterilizado'),
        ),
    ]
