# Generated by Django 4.2.7 on 2025-11-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_visita_estado_visita_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad',
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(default='2023-01-01', verbose_name='Fecha de Nacimiento'),
        ),
    ]
