# Generated by Django 4.2.7 on 2025-10-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_mascota_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='foto',
        ),
    ]
