# Generated by Django 4.2.7 on 2025-10-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_alter_mascota_esterilizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='visita',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
